import { StateSchema, type GraphNode, StateGraph,START,END } from "@langchain/langgraph"
import z from "zod"
import { MistralModel, GoogleModel, CohereModel } from "../Ai/model.ai.js"
import { createAgent, HumanMessage, providerStrategy, } from "langchain"


const State = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_FeedBack: z.string().default(""),
    })
})

const solutionNode: GraphNode<typeof State> = async (State) => {
    // const question = State.problem[0].text
    const [MistralResponse, cohoreResponse] = await Promise.all([
        MistralModel.invoke(State.problem),
        CohereModel.invoke(State.problem)
    ])

    return {
        solution_1: MistralResponse.text,
        solution_2: cohoreResponse.text
    }
}

const judgenode: GraphNode<typeof State> = async (State) => {
    const { problem, solution_1, solution_2 } = State

    const judge = createAgent({
        model: GoogleModel,
        tools: [],
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_FeedBack: z.string().default(""),
        })),
        systemPrompt: `you are a judge tasked with the evaluating two solution 
        generated by different ai model please provide a score out of 10 for each solution with along FeedBack for the score `
    })
    const judgeresponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                problem ${problem}
                solution 1 ${solution_1}
                solution 2 ${solution_2}

                please evaluate the solution and provide score and FeedBack
                `)
        ]
    })

    const {
        solution_1_score,
        solution_2_score,
        solution_FeedBack,
    } = judgeresponse.structuredResponse

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_FeedBack,
            
        }
    }
}

const graph = new StateGraph(State)
    .addNode("solution", solutionNode)
    .addNode("judges", judgenode)
    .addEdge(START, "solution")
    .addEdge("solution", "judges")
    .addEdge("judges", END)
    .compile()

export default async function rungraph(problem: string) {
    const result = await graph.invoke({
        problem
    })

    return result
}